### ISSUE TITLE
Alternative to MATRIX_OS/MATRIX_ARCH for build combinations

### ISSUE THREAD

**Issue by koshatul** [make-files/issues#19]
As it stands if there is a complex set of build targets, the `MATRIX_OS`/`MATRIX_ARCH` aren't up to scratch and there isn't a way to bypass them.

Example, building for:
- darwin/386
- darwin/amd64
- freebsd/386
- freebsd/amd64
- freebsd/arm
- linux/386
- linux/amd64
- linux/arm
- netbsd/386
- netbsd/amd64
- netbsd/arm
- openbsd/386
- openbsd/amd64
- windows/386
- windows/amd64

where `arm` isn't on all `OS` combinations.

Starting this issue for discussion of alternatives or considerations for bypassing the matrix/replacing it.

**Comment by jmalloc** [comment]
I am unsure whether the matrix idea should even be retained.  Perhaps, it's easier both to understand and configure if we just require the user to specify the exact combinations required. At least, I think I prefer this approach over retaining the matrix and then also supporting explicit inclusions/exclusions.

My personal and work projects have produced three largely non-overlapping use cases:
- User facing CLIs, which so far have been `amd64` for `linux` and `macos`, and less frequently `windows`
- Docker images, `linux/amd64` only
- Raspberry PI projects, `linux/arm` only

---

> where `arm` isn't on all `OS` combinations.

Is this a Go limitation, or something needed for your use case?

**Comment by koshatul** [comment]
I guess Go doesn't build `windows/arm`, but I don't know if I'd say that's a Go limitation or not.

Maybe the matrix can go the way of the dodo, the extreme example:
```Makefile
BUILD_TARGET += darwin/386
BUILD_TARGET += darwin/amd64
BUILD_TARGET += freebsd/386
BUILD_TARGET += freebsd/amd64
BUILD_TARGET += freebsd/arm
BUILD_TARGET += linux/386
BUILD_TARGET += linux/amd64
BUILD_TARGET += linux/arm
BUILD_TARGET += netbsd/386
BUILD_TARGET += netbsd/amd64
BUILD_TARGET += netbsd/arm
BUILD_TARGET += openbsd/386
BUILD_TARGET += openbsd/amd64
BUILD_TARGET += windows/386
BUILD_TARGET += windows/amd64
``` 

doesn't look that bad, and most projects would just be
```Makefile
BUILD_TARGET += darwin/amd64 linux/386 linux/amd64
```
or
```Makefile
BUILD_TARGET += darwin/amd64
BUILD_TARGET += linux/386 linux/amd64
BUILD_TARGET += linux/arm5 linux/arm7
```

**Comment by jmalloc** [comment]
Yeah, even with this many entries, I think I prefer this to any kind of inclusion/exclusion mechanism atop the matrix.  The user could always build this using a matrix of their own, or whatever logic.

**Comment by jmalloc** [comment]
Just a reminder to whomever does the PR that the default behavior of building on the current OS and architecture needs to be retained. This is what `make build` does, regardless of the contents of the matrix.

Also, the variable name will need to begin with `GO_`... `GO_BUILD_TARGET` isn't bad, but because of the behavior noted above it's not actually used in `build` so this is possibly a bit misleading.  It *is* used by the `debug`, `release` and `archive` targets. 

Some suggestions:
- `GO_TARGET(S)`
- `GO_PLATFORM(S)` ("platform" is already used inside the makefile to refer to the OS/arch pair)

**Comment by koshatul** [comment]
I just pulled `BUILD_TARGET` out of my head, I actually didn't think it was a great one to use anyway.

I like `GO_TARGET`.

**Comment by jmalloc** [comment]
Kosh has changed the files to a singular GO_MATRIX variable, with a warning that GO_MATRIX_ARCH and GO_MATRIX_OS are deprecated.
