### ISSUE TITLE
Loading custom PHP ini files breaks loading extensions

### ISSUE THREAD

**Issue by ezzatron** [make-files/issues#22]
I've been trying to add better support for different coverage drivers to the PHP makefiles. One thing I noticed, is that specifying a custom INI stops the system's default INI from being loaded at all.

This means that `extension_dir` does not get set correctly, and basically makes it impossible to simultaneously have a custom INI and load a PECL extension at the same time. Under macOS, Homebrew no longer supplies extensions as packages, and they must be installed with PECL, so this is a pretty tricky situation.

I think it might be simplest to ditch custom INI files, and instead allow INI customization only with `-d` options passed to the runtime.

**Comment by jmalloc** [comment]
> I think it might be simplest to ditch custom INI files, and instead allow INI customization only with `-d` options passed to the runtime.

Could we instead set `PHP_INI_SCAN_DIR` to some directory with the repo? If not, then fair enough, no strong objection to using `-d` arguments (presumably set via some Make variable).

**Comment by ezzatron** [comment]
I could have sworn the "extra" ini dir was a compile-time-only thing. But [the manual](https://www.php.net/manual/en/configuration.file.php#configuration.file.scan) does seem to suggest that you can set it at runtime, *and* you can specify multiple paths.

So I might be able to utilize some kind of list to reimplement the current behaviour, but I will have to change the INI file paths. Maybe something like this structure:

```
test/etc/
  php/
    phpunit/
      *.ini
    peridot/
      *.ini
    kahlan/
      *.ini    <- used only for Kahlan
    *.ini      <- used in all test runners
```

**Comment by jmalloc** [comment]
That seems reasonable to me, *but* I should say that I don't actually have a use-case for it. I'm reasonably sure the only remaining INI settings I have could easily be handled with `-d`.  So your call.

**Comment by ezzatron** [comment]
That's a fair point. I might just rip out the current implementation for now since it's problematic.

**Comment by ezzatron** [comment]
Removed in https://github.com/make-files/pkg-php/commit/c1917b7f532005808f56d99b4c6bb4d824a9a554
