### ISSUE TITLE
Semantics of a new "with-" prefix for mixins

### ISSUE THREAD

**Issue by ezzatron** [make-files/issues#28]
This came up in verbal discussion. The example I raised was two differing use cases:

- Webpack as the primary build tool for a project
- Webpack as a secondary build tool, used via something like Grunt or Gulp

It's likely that in both cases, having some standard targets such as `build`, `release`, `debug` would be desirable. But the second use case is not something that can be solved with an extensible double-colon target. The end user needs a way to specify which build tool should be used when, for example, `make build` is run.

We agreed upon a convention where tools like this would have two separate mixins (Webpack used as an example):

- `-include .makefiles/pkg/js/v1/with-webpack.mk` (adds Webpack support but doesn't hijack any of the "standard" targets)
- `-include .makefiles/pkg/js/v1/webpack.mk` (indicates that Webpack is the primary build tool, makes Webpack responsible for things like `make build`)

In practice, `with-webpack` will probably be included automatically when a `webpack.config.js` file is present, but I think that's also fine.

We also talked about what rules `with-` mixins should follow. I think the only rule we established is that they never add anything to double-colon targets.

**Comment by jmalloc** [comment]
> We also talked about what rules `with-` mixins should follow. I think the only rule we established is that they never add anything to double-colon targets.

For clarity, it wasn't just "double colon" targets, but *any* of the "standard" targets. It's probably the case right now that all of the standard targets *are* defined with double-colons, but I'm not confident that will always be true.

**Comment by ezzatron** [comment]
Just updating this task to note that we decided to flip the semantics of the `with-` prefix. The makefiles with a `with-` prefix will now tend to be the ones that are expected to be included manually, and the non-prefixed ones will be the automatic includes.
