### ISSUE TITLE
Should we use autoconf to better handle cross-platform concerns?

### ISSUE THREAD

**Issue by jmalloc** [make-files/issues#5]
- https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#Introduction
- https://autotools.io

A lot of content and background to get through with this, but ultimately it's about producing cross-platform makefiles that are easy to use for the end user.  There's also [automake](https://www.gnu.org/software/automake/) in the mix, but I can't say I properly understand their relationship yet.

Updates:

- This may not be appropriate for makefiles that perform cross-compilation, as it the case with the Go makefiles.
- Ok, it's generally much more concerned the C language, specifically, than I was aware. It does however have [features](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#Alternative-Programs) for checking for the presence of, and choosing between alternatives of various binary dependencies that need to be on the build machine.

**Comment by ezzatron** [comment]
Regarding automake, I found this [useful summary](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/autoconf.html#Automake) in autoconf's docs:

> The ubiquity of `make` means that a makefile is almost the only viable way to distribute automatic build rules for software, but one quickly runs into its numerous limitations. Its lack of support for automatic dependency tracking, recursive builds in subdirectories, reliable timestamps (e.g., for network file systems), and so on, mean that developers must painfully (and often incorrectly) reinvent the wheel for each project. Portability is non-trivial, thanks to the quirks of `make` on many systems. On top of all this is the manual labor required to implement the many standard targets that users have come to expect (`make install`, `make distclean`, `make uninstall`, etc.). Since you are, of course, using Autoconf, you also have to insert repetitive code in your `Makefile.in` to recognize `@CC@`, `@CFLAGS@`, and other substitutions provided by `configure`. Into this mess steps *Automake*. Automake allows you to specify your build needs in a `Makefile.am` file with a vastly simpler and more powerful syntax than that of a plain makefile, and then generates a portable `Makefile.in` for use with Autoconf. For example, the `Makefile.am` to build and install a simple “Hello world” program might look like:
>
>     bin_PROGRAMS = hello
>     hello_SOURCES = hello.c
>
> The resulting `Makefile.in` (~400 lines) automatically supports all the standard targets, the substitutions provided by Autoconf, automatic dependency tracking, `VPATH` building, and so on. `make` builds the `hello` program, and `make install` installs it in `/usr/local/bin` (or whatever prefix was given to configure, if not `/usr/local`).
>
> The benefits of Automake increase for larger packages (especially ones with subdirectories), but even for small programs the added convenience and portability can be substantial. And that's not all...

**Comment by jmalloc** [comment]
I think we can close this as unwanted?

**Comment by ezzatron** [comment]
I think so.
